/**
 * Machine-readable error codes for consistent API responses.
 */
export const ErrorCodes = {
  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

  // Leads
  LEAD_NOT_FOUND: 'LEAD_NOT_FOUND',
  DUPLICATE_LEAD: 'DUPLICATE_LEAD',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',

  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
};

export default ErrorCodes;
