/**
 * Application-wide constants.
 */

export const LEAD_STATUSES = {
  NEW: 'NEW',
  QUALIFIED: 'QUALIFIED',
  NOT_QUALIFIED: 'NOT_QUALIFIED',
  OPPORTUNITY: 'OPPORTUNITY',
  CONVERTED: 'CONVERTED',
};

export const VALID_TRANSITIONS = {
  [LEAD_STATUSES.NEW]: [LEAD_STATUSES.QUALIFIED, LEAD_STATUSES.NOT_QUALIFIED],
  [LEAD_STATUSES.QUALIFIED]: [LEAD_STATUSES.OPPORTUNITY, LEAD_STATUSES.NOT_QUALIFIED],
  [LEAD_STATUSES.OPPORTUNITY]: [LEAD_STATUSES.CONVERTED],
  [LEAD_STATUSES.NOT_QUALIFIED]: [LEAD_STATUSES.NEW],
  [LEAD_STATUSES.CONVERTED]: [],
};

export const PAYMENT_STATUSES = {
  PENDING: 'PENDING',
  RECEIVED: 'RECEIVED',
};

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 50,
};
